<a href="https://colab.research.google.com/github/rajkonkret/PythonAnalizaDanych/blob/master/cwiczenie1_analiza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Początek programu
**pogrubiony tekst**<br>
Nowa linia
# Nowa sekcja
## Nowa sekcja

In [1]:
print("Witaj w notatniku...")

Witaj w notatniku...


In [2]:
a=5
b=6

In [3]:
print(a, b)

5 6


In [ ]:
c = 9

Celowo nie uruchamiam wiersza c = 9 by wygenerować bład


In [4]:
print(c)

NameError: name 'c' is not defined

# Biblioteka NumPy

Napisana w c do szybkich operacji na danych tablicowych<br>
podstawowy element ndarray

In [5]:
!pip install numpy
# !pip install numpy==2.2.0

In [6]:
import numpy as np

lista = [2, 4, 6, 8, 10]
print(lista)
lista

[2, 4, 6, 8, 10]


[2, 4, 6, 8, 10]

In [7]:
a = np.array(lista)
print(a)

[ 2  4  6  8 10]


In [8]:
print(a.dtype)

int64


int64 - 8 bajtów

In [9]:
print(type(a))

<class 'numpy.ndarray'>


In [10]:
print(a.shape)

(5,)


In [11]:
p = np.zeros((3,3))
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
print(p.dtype)

float64


In [14]:
q = np.ones((2, 2))
print(q)
q.dtype

[[1. 1.]
 [1. 1.]]


dtype('float64')

In [16]:
r = np.full((2,2),4)
print(r)
print(r.dtype)

[[4 4]
 [4 4]]
int64


In [17]:
s = np.eye(4)
print(s)
print(s.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64


In [18]:
t = np.random.random((3,3))
print(t)
print(t.dtype)

[[0.26154255 0.52564812 0.76794791]
 [0.6436899  0.22858924 0.17308316]
 [0.94831344 0.34665436 0.66157699]]
float64


In [19]:
lista2 = [[5,6], [7,8]]
b = np.array(lista2)
print(lista2)
print(b)

[[5, 6], [7, 8]]
[[5 6]
 [7 8]]


ravel() - spłaszczenie

In [20]:
print(b.ravel())

[5 6 7 8]


In [21]:
print(b[0])

[5 6]


In [23]:
print(b[0, 0])
print(b[0, 1])

5
6


In [24]:
print(np.float64(21))

21.0


In [25]:
print(np.int64(22.0))

22


In [26]:
print(np.bool(21))

True


In [27]:
print(np.float64(True))

1.0


In [28]:
arr = np.arange(1, 11, dtype=np.float64)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [29]:
print(arr.dtype)

float64


reshape() - zmiana kształtu

In [30]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
new_arr = arr.reshape(4, 3)
print(new_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [32]:
new_arr = arr.reshape(3, 4)
print(new_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
new_arr = arr.reshape(3, 5)
print(new_arr)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [35]:
new_arr = arr.reshape(3, 3)
print(new_arr)

ValueError: cannot reshape array of size 12 into shape (3,3)

ravel() zwraca widok, operacje na nowym widoku "tablicy" wpływają na zmiany oryginalnej tablicy

In [39]:
print(new_arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


flatten() - spłaszcza ale robi kopię\
zmiany nie wpływają na oryginalną tablicę

In [38]:
print(new_arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [40]:
flat = new_arr.flatten()
rav = new_arr.ravel()

In [41]:
flat[0] = 999
rav[1] = 888

In [42]:
print(new_arr)

[[  0 888   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


transpose() - zaminia osie

In [43]:
print(new_arr.transpose())

[[  0   4   8]
 [888   5   9]
 [  2   6  10]
 [  3   7  11]]


resize() - zmienia rozmiar tablicy
zmienia oryginalna tablice in-place
brakujące eleemnty wypełni zerami

In [45]:
new_arr.resize(1,12)
print(new_arr)

[[  0 888   2   3   4   5   6   7   8   9  10  11]]


In [46]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
